#!/usr/bin/env bash

# removes all files generated by CiTO_crawl.py except for the "OC-compliant_CiTO_graphs" directory (which contains the OpenCitations-compliant graphs)

cd CiTOCrawler
rm crawledPages.csv
rm -r crawled_pages
rm -r crawled_RDF
rm -r crawled_CiTO
rm CiTOGraph.json
rm stats.txt
