#!/usr/bin/env bash

# removes all files generated by CiTO_crawl.py except for the "OC-compliant_CiTO_graphs" directory (which contains the OpenCitations-compliant graphs)

cd CiTOCrawler
rm crawledPages.csv
rm -rf crawled_pages
rm -rf crawled_RDF
rm -rf crawled_CiTO
rm CiTOGraph.json
rm stats.txt
