#!/usr/bin/env bash

# removes all files generated by CiTO_crawl.py except for:
#  - the "CiTO_graphs" directory (which contains the OpenCitations-compliant graphs)
#  - crawledPages.csv (which keeps track of the visited pages in past runs of CiTOCrawl.py)

cd CiTOCrawler
rm -r crawled_pages
rm -r crawled_rdf
for f in CiTO_g_*.json; do rm "$f"; done
rm CiTOGraph.json
rm stats.txt
