#!/usr/bin/env bash

# removes all files generated by CiTO_crawl.py except for:
#  - the "OC-compliant_CiTO_graphss" directory (which contains the OpenCitations-compliant graphs)
#  - crawledPages.csv (which keeps track of the visited pages in past runs of CiTOCrawl.py)

cd CiTOCrawler
rm -r crawled_pages
rm -r crawled_RDF
rm -r crawled_CiTO
rm CiTOGraph.json
rm stats.txt
